server.port=18082
logging.file.name=logs/app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
